# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab7fc0ead3c8320f7770b71e0df3568d2f105792668eae99fd0ffe666611c7a8e87f2ff8291bcc264b39aa1f8f73a83e8d6379039b385a6a7f97f080f285cc72

test:
  secret_key_base: 15ab186ac4ce17cb55defc5cb5f6690c50456a948ee717b3bcd60af1e54b7a12f005b02cf3250a46d4b7f48431f7920beced29e140fe052a02c3288a58c470d8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
